const CODE_RESPONSE_SUCCESS = 200; //成功
const CODE_RESPONSE_FAILURE = 400; //失败
const CODE_RESPONSE_UNAUTHORIZED = 401; //未认证（签名错误）
const CODE_RESPONSE_NOT_FOUND = 404; //接口不存在
const CODE_RESPONSE_SERVER_ERROR = 500; //服务器内部错误

const MESSAGE_RESPONSE_SUCCESS = "请求成功";
const MESSAGE_RESPONSE_FAILURE = "请求失败";
const MESSAGE_RESPONSE_UNAUTHORIZED = "未认证（签名错误）";
const MESSAGE_RESPONSE_NOT_FOUND = "接口不存在";
const MESSAGE_RESPONSE_SERVER_ERROR = "服务器内部错误";

export default {
    CODE_RESPONSE_SUCCESS,
    CODE_RESPONSE_FAILURE,
    CODE_RESPONSE_UNAUTHORIZED,
    CODE_RESPONSE_NOT_FOUND,
    CODE_RESPONSE_SERVER_ERROR,
    MESSAGE_RESPONSE_SUCCESS,
    MESSAGE_RESPONSE_FAILURE,
    MESSAGE_RESPONSE_UNAUTHORIZED,
    MESSAGE_RESPONSE_NOT_FOUND,
    MESSAGE_RESPONSE_SERVER_ERROR
}